#!/usr/bin/env php
<?php
namespace iflow;

require __DIR__ . '/vendor/autoload.php';

use \iflow\router\lib\RouterAnnotation;

// 应用初始化
#[RouterAnnotation([
    'app'
])] // 定义路由注解
class MyApplication extends App {
    public function runApp()
    {
        $this->run(static::class);
    }
}

(new MyApplication()) -> runApp();
