#!/usr/bin/env php
<?php
namespace iflow;

require __DIR__ . '/vendor/autoload.php';

// 应用初始化
#[\iflow\router\lib\RouterAnnotation([
     'iflow\app\live_web',
     'iflow\app\controller'
])] // 定义路由注解
class MyApplication extends App {
    public function runApp()
    {
        $this->run(static::class);
    }
}

(new MyApplication()) -> runApp();