<?php

namespace iflow\template\Adapter\Regx\implement\Tag;

use iflow\template\Adapter\Regx\implement\Abstracts\TagAbstract;
use iflow\template\Adapter\Regx\Interfaces\TagInterface;

/**
 * @desc 未定义TAG 移至此处处理
 */
class DefaultTag extends TagAbstract {

    public function parser(string $tag, string $html, array $args): TagInterface {
        parent::parser($tag, $html, $args); // TODO: Change the autogenerated stub

        return $this;
    }

    public function toHtml(): string {
        $_htmlTag = $this->attrs['html-tag'] ?? $this->tag;
        $attribute = $this->attributeToString();
        $endHtmlLabel = $this->isCloseLabel ? '' : "</{$_htmlTag}>";
        $startHtmlLabel = sprintf($this->isCloseLabel ? '<%s %s />' : '<%s %s>',
            $_htmlTag, $attribute
        );
        return sprintf('%s %s %s',
            $startHtmlLabel, $this->isCloseLabel ? '' : ($this->html ?: $this->source), $endHtmlLabel);
    }


}