<?php

namespace iflow\template\Adapter\Regx\implement\Tag;

use iflow\template\Adapter\Regx\implement\Abstracts\TagAbstract;
use iflow\template\Adapter\Regx\Interfaces\TagInterface;

class ForeachTag extends TagAbstract {

    protected string $instructionCode = '';

    public function parser(string $tag, string $html, array $args): TagInterface {
        parent::parser($tag, $html, $args); // TODO: Change the autogenerated stub

        $this->html = $this->toPhpScript($html);
        return $this;
    }

    /**
     * @param string $templateCode
     * @return string
     */
    protected function toPhpScript(string $templateCode): string {
        $this->html = "<?php foreach (%s): ?>%s<?php endforeach; ?>";

        $this->instructionCode = $this->instructionCode ?: sprintf(
            "%s as %s => %s",
            $this->attrs['datum'] ?? '[]',
            $this->setParamsStartCode($this->attrs['item'] ?? 'item'),
            $this->setParamsStartCode($this->attrs['key'] ?? 'index'),
        );

        return sprintf($this->html, $this->instructionCode, $templateCode);
    }

}