<?php

namespace iflow\template\Adapter\Regx\implement\Tag;

use iflow\template\Adapter\Regx\implement\Abstracts\TagAbstract;
use iflow\template\Adapter\Regx\Interfaces\TagInterface;

class PhpScriptTag extends TagAbstract {

    public function parser(string $tag, string $html, array $args): TagInterface {
        parent::parser($tag, $html, $args); // TODO: Change the autogenerated stub
        $this->html = $this->toPhpScript($html);

        return $this;
    }


    public function toPhpScript(string $phpCode): string {
        return sprintf("<?php %s ?>", $phpCode);
    }

}