<?php


namespace iflow\annotation\lib\value;


#[\Attribute]
class Inject extends Value {

    /**
     * 获取当前值是否存在并按照类型生成新的值
     * @param \ReflectionParameter|\ReflectionProperty $ref
     * @param $object
     * @param array $args
     * @return mixed
     * @throws \ReflectionException
     */
    public function getValue(\ReflectionParameter|\ReflectionProperty $ref, $object, array &$args = []): mixed
    {
        $value = parent::getValue($ref, $object, $args); // TODO: Change the autogenerated stub
        if (!$value) {
            $types = app()->getParameterType($ref);
            if (count($types) > 0 && class_exists($types[0])) {
                $value = app($types[0]);
            }
        }
        return $value;
    }

}
