<?php

namespace iflow\swoole\implement\Services\Queue;

use iflow\swoole\abstracts\ServicesAbstract;

class Services extends ServicesAbstract {


    public function start() {
        parent::start(); // TODO: Change the autogenerated stub
    }

}