<?php

namespace iflow\swoole\implement\Services\Queue;

use iflow\Container\implement\annotation\tools\data\Inject;
use iflow\swoole\abstracts\ServicesAbstract;
use iflow\swoole\implement\Services\Queue\implement\Topics\Topic;

class Services extends ServicesAbstract {

    #[Inject]
    protected Topic $topic;

    public function start() {
        parent::start(); // TODO: Change the autogenerated stub
    }

}