<?php


namespace iflow\http;

use iflow\event\Event;
use iflow\http\lib\Request;
use iflow\http\lib\Response;
use iflow\http\lib\Service;
use iflow\initializer\appSurroundings;
use iflow\initializer\Config;
use iflow\initializer\Error;
use iflow\initializer\Helpers;
use iflow\initializer\initializer;
use iflow\log\Log;

class App extends \iflow\App {

    protected array $initializers = [
        Config::class,
        Helpers::class,
        Event::class,
        Log::class,
        Error::class,
        appSurroundings::class,
        initializer::class
    ];

    public function initializer(): App {
        parent::initializer(); // TODO: Change the autogenerated stub
        event('RequestVerification', new Request(), new Response(), microtime(true));
        return $this;
    }
}