<?php


namespace iflow\http;


use iflow\http\lib\Request;
use iflow\http\lib\Response;
use iflow\initializer\annotationInitializer;
use iflow\initializer\appSurroundings;
use iflow\initializer\Config;
use iflow\initializer\Error;
use iflow\initializer\initializer;
use iflow\log\Log;

class App extends \iflow\App
{
    protected array $initializers = [
        Config::class,
        Log::class,
        Error::class,
        appSurroundings::class,
        annotationInitializer::class,
        initializer::class
    ];

    protected Request $request;
    protected Response $response;


    protected function initializer(): void
    {
        parent::initializer(); // TODO: Change the autogenerated stub

        $this->request = new Request();
        $this->response = new Response();
        $this->request();
    }

    public function request()
    {
        $initializer = new \iflow\Swoole\Services\Http\lib\initializer();
        $initializer -> services = new \iflow\http\lib\service($this);
        $initializer -> __initializer($this->request, $this->response);
    }
}