<?php

namespace iflow\annotation\value;

use iflow\Container\implement\annotation\tools\data\Inject;
use Reflector;

#[\Attribute(\Attribute::TARGET_PROPERTY|\Attribute::TARGET_PARAMETER)]
class CloneInject extends Inject {

    public function getValue(Reflector $ref, ?object $object = null, array &$args = []): mixed {
        $value = parent::getValue($ref, $object, $args); // TODO: Change the autogenerated stub

        if (is_object($value)) return clone $value;
        return $value;
    }

}