<?php


namespace iflow\template\lib\document\Tag;


use iflow\template\lib\config;
use iflow\template\lib\document\abstracts\tagAbstract;
use iflow\template\lib\document\document;
use iflow\template\lib\document\exception\templateException;
use iflow\template\lib\document\Parser\DOMNodeParser;
use iflow\template\lib\document\Parser\ParserHtml;

class includeTag extends tagAbstract
{

    protected array $hiddenAttributes = [
        "file"
    ];

    protected document $includeDocument;

    public function parser(DOMNodeParser $node, config $config, ParserHtml $parserHtml): static
    {
        parent::parser($node, $config, $parserHtml); // TODO: Change the autogenerated stub
        $file = $this->config -> getViewRootPath().($this->attributes['file'] ?: "");
        if (!file_exists($file)) {
            throw new templateException("include template file not does exists");
        }
        $this->includeDocument = new document(file_get_contents($file));

        // 将导入的HTML 代码解析为 PHPCode
        $this->html = $this->parserHtml -> traverseNodes(
            $this->includeDocument -> getElementsByTagName('library') -> item(0)
        );
        return $this;
    }
}