<?php


namespace iflow\template\lib\document\Tag;


use iflow\template\lib\config;
use iflow\template\lib\document\abstracts\tagAbstract;
use iflow\template\lib\document\Parser\DOMNodeParser;
use iflow\template\lib\document\Parser\ParserHtml;

class Literal extends tagAbstract
{

    protected array $hiddenAttributes = ["tag"];

    public function parser(DOMNodeParser $node, config $config, ParserHtml $parserHtml): static
    {
        parent::parser($node, $config, $parserHtml); // TODO: Change the autogenerated stub
        $html = $this->node -> innerHtml();
        preg_match_all(
            "/(\<literal\>)([\s\S]*?)(\<\/literal\>)/i",
            $html,
            $html);
        $this->html = $html[2][0];
        return $this;
    }
}