<?php


namespace iflow\template\lib\document\Tag;


use iflow\template\lib\config;
use iflow\template\lib\document\abstracts\tagAbstract;
use iflow\template\lib\document\Parser\DOMNodeParser;
use iflow\template\lib\document\Parser\ParserHtml;

class PHPScript extends tagAbstract
{
    public string $tagName = "phpScript";

    protected array $hiddenAttributes = ['tag'];

    public function parser(DOMNodeParser $node, config $config, ParserHtml $parserHtml): static
    {
        parent::parser($node, $config, $parserHtml); // TODO: Change the autogenerated stub
        $this->html = sprintf("<?php %s ?>", $this->node -> nodeValue);
        return $this;
    }
}