<?php

namespace iflow\annotation\Db\Column;

final class ColumnType {

    CONST INT = 'INT';

    CONST SMALLINT = 'SMALLINT';

    CONST TINYINT = 'TINYINT';

    CONST BIGINT = 'BIGINT';

    CONST DOUBLE = 'DOUBLE';

    CONST FLOAT = 'FLOAT';

    CONST STRING = 'VARCHAR';

    CONST CHAR   = 'CHAR';

    CONST TEXT = 'TEXT';

    CONST SMALLTEXT = 'SMALLTEXT';

    CONST MEDIUMTEXT = 'MEDIUMTEXT';

    CONST LONGTEXT = 'LONGTEXT';

    CONST FULLTEXT = 'FULLTEXT';

    CONST BINARY = 'BINARY';

    CONST JSON = 'JSON';

    CONST DATETIME = 'DATETIME';

    CONST DATE = 'DATE';

    CONST TIMESTAMP = 'TIMESTAMP';

    CONST PG_NUMERIC = 'NUMERIC';

    CONST PG_TIMESTAMP_WITHOUT_TIME_ZONE = 'TIMESTAMP WITHOUT TIME ZONE';

    CONST PG_VARYING = 'VARYING';

    CONST PG_DECIMAL = 'DECIMAL';

}